export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FILLSTATE = "FILLSTATE";
export const LOGINAGENCY = "LOGINAGENCY";
export const UPDATEAGENCYPROFILE = "UPDATEAGENCYPROFILE";

// export const FRIEND_OFFLINE = "FRIEND_OFFLINE";
// export const RECEIVED_MESSAGE = "RECEIVED_MESSAGE";
// export const PAGINATE_MESSAGES = "PAGINATE_MESSAGES";
// export const INCREMENT_SCROLL = "INCREMENT_SCROLL";
// export const CREATE_CHAT = "CREATE_CHAT";
// export const ADD_USER_TO_GROUP = "ADD_USER_TO_GROUP";
// export const LEAVE_CURRENT_CHAT = "LEAVE_CURRENT_CHAT";

export const SET_SOCKET = "SET_SOCKET";
export const CHAT_EXISTS = "CHAT_EXISTS";
export const USER_ONLINE = "USER_ONLINE";
export const USER_OFFLINE = "USER_OFFLINE";
export const ALL_CHATS = "ALL_CHATS";
export const FRIENDS_ONLINE = "FRIENDS_ONLINE";
export const SET_CHATS = "SET_CHATS";
export const FRIEND_ONLINE = "FRIEND_ONLINE";
export const SENDER_TYPING = "SENDER_TYPING";
export const STOP_TYPING = "STOP_TYPING";
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_ALL_MESSAGES = "SET_ALL_MESSAGES";
export const SET_SEEN_MESSAGE = "SET_SEEN_MESSAGE";
export const DELETE_CHAT = "DELETE_CHAT";
export const BLOCK_CHAT = "BLOCK_CHAT";
export const UNBLOCK_CHAT = "UNBLOCK_CHAT";
export const FETCH_CHATS = "FETCH_CHATS";
export const EDIT_FETCH_CHATS = "EDIT_FETCH_CHATS";

// NOTIFICATION
export const REQUEST_CONSULTATION = "REQUEST_CONSULTATION";
export const STORE_ALL_CONSULTATIONS = "STORE_ALL_CONSULTATIONS";
export const DECLINE_CONSULTATION = "DECLINE_CONSULTATION";
export const UPDATE = "UPDATE";
export const DELETE_CONSULTATION = "DELETE_CONSULTATION";
export const NOTIFY = "NOTIFY";
export const STORE_NOTIFICATIONS = "STORE_NOTIFICATIONS";
export const SEEN_ALL_NOTIFY = "SEEN_ALL_NOTIFY";
export const RATE = "RATE";
