export const amenities = [
  {
    id: "Fully Furnished",
    item: "Fully Furnished",
    type: "table-furniture",
    name: "material-community",
  },
  {
    id: "Partly Furnished",
    item: "Partly Furnished",
    type: "table-furniture",
    name: "material-community",
  },
  {
    id: "Central A/C",
    item: "Central A/C",
    type: "coolant-temperature",
    name: "material-community",
  },
  {
    id: "Security",
    item: "Security",
    type: "pool",
    name: "material-community",
  },
  {
    id: "Shared pool",
    item: "Shared pool",
    type: "pool",
    name: "material-community",
  },
  {
    id: "Wardrobes",
    item: "Wardrobes",
    type: "wardrobe",
    name: "material-community",
  },
  {
    id: "Kitchen Applicances",
    item: "Kitchen Applicances",
    type: "utensils",
    name: "font-awesome-5",
  },
  {
    id: "Parking",
    item: "Parking",
    type: "car-alt",
    name: "font-awesome-5",
  },
  {
    id: "Balcony",
    item: "Balcony",
    type: "google-street-view",
    name: "material-community",
  },
  {
    id: "Garden",
    item: "Garden",
    type: "tree",
    name: "material-community",
  },
  {
    id: "Study",
    item: "Study",
    type: "book",
    name: "ionicon",
  },
  {
    id: "Shared Spa",
    item: "Shared Spa",
    type: "face-woman",
    name: "material-community",
  },
  {
    id: "View",
    item: "View",
    type: "google-street-view",
    name: "material-community",
  },
  {
    id: "Water View",
    item: "Water View",
    type: "water",
    name: "font-awesome-5",
  },
];
